[package]
name = "rusty_ray_tracer"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = "0.9.0"
smallvec = "1.13.2"
rayon = "1.10.0"
dashmap = {version= "6.0.1", features = ["rayon"]}
rand = "0.9.0-alpha.2"
rand_distr = "0.4.3"

[profile.test] # fixed
opt-level = 2