[package]
name = "rusty_ray_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.2.1"
noise = "0.7.0"
serde = {version="1.0", features = ["derive", "rc"]}
smallvec = "1.6"
rayon = "1.5.1"
dashmap = {version="5.0.0", features = ["rayon"]}
uuid = { version = "0.8.2", features = ["v4"] }

[profile.test] # fixed
opt-level = 2